import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/Providers";
import StatusCheckerProvider from "@/lib/StatusCheckerProvider";
import Preference from "./preference/Preference";
import { GoogleOAuthProvider } from "@react-oauth/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Establishment Recommendation System",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <StatusCheckerProvider>
                        <GoogleOAuthProvider clientId="1018735343493-7bm8mu5l1atav2hjpg1frcoo3fe3q67l.apps.googleusercontent.com">
                            <Preference>{children}</Preference>
                        </GoogleOAuthProvider>
                    </StatusCheckerProvider>
                </Providers>
            </body>
        </html>
    );
}
