import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/Providers";
import StatusCheckerProvider from "@/lib/StatusCheckerProvider";
import Preference from "./preference/Preference";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Establishment Recommendation System",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <StatusCheckerProvider>
                        <Preference>{children}</Preference>
                    </StatusCheckerProvider>
                </Providers>
            </body>
        </html>
    );
}
