export const Barangay = [
  {
    name:"Conception Uno",
    description:'Barangay Conception Uno formerly known as the Bayan-Bayanan (little town).',
    image:'images/1.jpg',
    establisments:[
      {
        Name:"Boy & Nita Ihaw-Ihaw Concepcion Branch",
        Type:"Restaurant",
        Location:"22 J. Molina, Corner L. De Guzman St, Marikina, 1800 Metro Manila",
        ContactNumber:"09",
      },
      {
        Name:"Glazed Unlimited Wings-Marikina",
        Type:"Restaurant",
        Location:"L. De Guzman St, corner J. Molina St, Marikina, 1807 Metro Manila",
        ContactNumber:"0285515828",
      },
      {
        Name:"Goto Bob",
        Type:"Restaurant",
        Location:"L. De Guzman St, Marikina, 1800 Metro Manila",
        ContactNumber:"09",
      },
      {
        Name:"Aegean Grill and Shawarma Station (Turkish Resto)",
        Type:"Restaurant",
        Location:"14, 1800 Candazo St, Marikina, 1800 Metro Manila",
        ContactNumber:"09182328723",
      },
      {
        Name:"Mcdonalds Concepcion Branch",
        Type:"Restaurant",
        Location:"20 Bayan-Bayanan Ave, Marikina, 1807 Metro Manila",
        ContactNumber:"0289971916",
      },
      {
        Name:"Mang Inasal Concepcion Branch",
        Type:"Restaurant",
        Location:"4 Bayan-Bayanan Ave, Marikina, 1807 Metro Manila",
        ContactNumber:"09",
      },
      {
        Name:"Jenny Ramen Food House",
        Type:"Restaurant",
        Location:"14 Bayan-Bayanan Ave, Marikina, 1807 Metro Manila",
        ContactNumber:"09957254193",
      },
      {
        Name:"Casa Mojica",
        Type:"Restaurant",
        Location:"17 E Gonzales St, Marikina, 1807 Metro Manila",
        ContactNumber:"09177040664",
      },
      {
        Name:"Jollibee E. Santos Bayan-Bayanan",
        Type:"Restaurant",
        Location:"20 Bayan-Bayanan Ave, Marikina, 1807 Metro Manila",
        ContactNumber:"0289971916",
      },
      {
        Name:"Pandecielo",
        Type:"Restaurant",
        Location:"8 J. Molina Corner, E G Manalo St, Marikina, 1807 Metro Manila",
        ContactNumber:"0286608591",
      },
      {
        Name:"Marikina St. Vincent General Hospital",
        Type:"Health Facility",
        Location:"35 Bayan-Bayanan Ave, Marikina, 1800 Metro Manila",
        ContactNumber:"0289480314",
      },
      {
        Name:"Golden Shepherd Laboratory and Health Diagnostic Services",
        Type:"Health Facility",
        Location:"35 Bayan-Bayanan Ave, Marikina, 1807 Metro Manila",
        ContactNumber:"09175683180",
      },
      {
        Name:"Conception Uno Barangay Hall",
        Type:"Government",
        Location:"J. Molina, Marikina, 1800 Metro Manila",
        ContactNumber:"None",
      },
      {
        Name:"Concepcion Uno Health Center",
        Type:"Government",
        Location:"20 A. de Leon St, Marikina, 1800 Metro Manila",
        ContactNumber:"09321487016",
      },
    ],
  },
  {
    name:"Sto. Nino",
    description:'A city in Marikina',
    image:"images/2.jpg",
    establisments:[
      {
        Name:"McDonalds JP Rizal Marikina",
        Type:"Restaurant",
        Location:" 439 J. P. Rizal St, Marikina, 1805 Metro Manila",
        ContactNumber:"02 8888 6236 ",
      },
      {
        Name:"Lola Helen Panciteria",
        Type:"Restaurant",
        Location:"425 J. P. Rizal St, Marikina, 1800 Metro Manila",
        ContactNumber:"09275470111",
      },
      {
        Name:"Comedor by Miguel and Maria",
        Type:"Restaurant",
        Location:"2f Mayor Gil Fernando Ave, Marikina, 1800 Metro Manila",
        ContactNumber:"02 8880 2031",
      },
      {
        Name:"Lamp Quarters",
        Type:"Restaurant",
        Location:"Mayor Gil Fernando Avenue Centro De Buenviaje Sto. Nino, Marikina, 1800 Metro Manila",
        ContactNumber:"09176520324",
      },
      {
        Name:"Premier The Samgyupsal Marikina",
        Type:"Restaurant",
        Location:" lot 3 block, 4 Mayor Gil Fernando Ave, Brgy, Marikina, 1800 Metro Manila",
        ContactNumber:"02 8365 8342",
      },
      {
        Name:"Cardiac Delights",
        Type:"Restaurant",
        Location:" 59 D Katipunan St, Marikina, 1807 Metro Manila",
        ContactNumber:"09770741597",
      },
      {
        Name:"KCQ Steak and Gril",
        Type:"Restaurant",
        Location:"33 Katipunan St, Marikina, 1800 Metro Manila",
        ContactNumber:"09232015304",
      },
      {
        Name:"Hippers Bar and Resto Marikina",
        Type:"Restaurant",
        Location:"Barangay, 7 Mayor Gil Fernando ave. Cor. Guerilla st. Brgy, Gil fernando avenue, Marikina, 1800 Metro Manila",
        ContactNumber:"09536471195",
      },
      {
        Name:"Milenya",
        Type:"Restaurant",
        Location:"8 Mayor Gil Fernando Ave, Extension, Marikina, 1800 Metro Manila",
        ContactNumber:" 09177013059",
      },
      {
        Name:"Gotobox",
        Type:"Restaurant",
        Location:"8 Mayor Gil Fernando Ave, Marikina, 1800 Metro Manila",
        ContactNumber:"09176277952",
      },
      {
        Name:"Mercury Drug",
        Type:"Health Facility",
        Location:"368 J. P. Rizal St, Marikina, 1800 Metro Manila",
        ContactNumber:"09",
      },
      {
        Name:"The Generics Pharmacy",
        Type:"Health Facility",
        Location:"opposite Marikina Sports Complex, 25 Shoe Avenue corner, 1800 P. dela Paz St, Marikina",
        ContactNumber:"0270053031",
      },
      {
        Name:"Etg Pharmacy (Cirma St.)",
        Type:"Health Facility",
        Location:"306 Cirma St., Santo Nio, Marikina, Metro Manila",
        ContactNumber:"0283305426",
      },
      {
        Name:" Easymed Pharmacy",
        Type:"Health Facility",
        Location:"E Jacinto St, Marikina, 1800 Metro Manila",
        ContactNumber:"09",
      },
      {
        Name:"Dela Paz Pharmacy",
        Type:"Health Facility",
        Location:"348 J. P. Rizal St, Marikina, 1800 Metro Manila",
        ContactNumber:"09",
      },
      {
        Name:"Livewell Pharmacy",
        Type:"Health Facility",
        Location:"303 E dela Paz St, Marikina, 1800 Metro Manila",
        ContactNumber:"09",
      },
      {
        Name:"Marikina Valley Medical Center",
        Type:"Health Facility",
        Location:"Sumulong Hwy, Marikina, 1800 Metro Manila",
        ContactNumber:"0286822222",
      },
      {
        Name:"Amang Rodriguez Memorial Medical Center",
        Type:"Health Facility",
        Location:"Sumulong Hwy, Marikina, 1800 Metro Manila",
        ContactNumber:"0289415854",
      },
      {
        Name:"VT Maternity Hospital",
        Type:"Health Facility",
        Location:"22 Guerilla St. Toyota Ave, Marikina, 1800 Metro Manila",
        ContactNumber:"0289426669",
      },
      {
        Name:"Marikina Sports Center",
        Type:"Landmark",
        Location:"24 Sumulong Hwy, Marikina, 1800 Metro Manila",
        ContactNumber:"0286829573",
      },
      {
        Name:"SF Direct Sto. Niño Fire Station",
        Type:"Government",
        Location:"32 E. Manalo Corner E. Mendoza, Sto. Nino, Marikina, 1800 Metro Manila",
        ContactNumber:"0289487509",
      },
      {
        Name:"Marikina City Fire Station - Extension Office",
        Type:"Government",
        Location:"2 E Jacinto St, Marikina, 1800 Metro Manila",
        ContactNumber:"2739629",
      },
      {
        Name:"Marikina City Police Substation 3",
        Type:"Government",
        Location:"S Dela Paz St, Marikina, 1800 Metro Manila",
        ContactNumber:"0234962742",
      },
    ],
  },
  {
    name:"Parang",
    description:'Parang is one of the most populated barangays in Marikina City.',
    image:"images/3.jpg",
    establisments:[
      {
        Name:"Kalma UNLTD & Grill",
        Type:"Restaurant",
        Location:"22 J. Molina, Corner L. De Guzman St, Marikina, 1800 Metro Manila",
        ContactNumber:"09",
      },
      {
        Name:"Carlden Pizza Place",
        Type:"Restaurant",
        Location:"L. De Guzman St, corner J. Molina St, Marikina, 1807 Metro Manila",
        ContactNumber:"(02) 8551 5828",
      },
      {
        Name:"Pot-Ling Cuisin",
        Type:"Restaurant",
        Location:" L. De Guzman St, Marikina, 1800 Metro Manila",
        ContactNumber:"None",
      },
      {
        Name:"Jollibee - Parang",
        Type:"Restaurant",
        Location:" 14, 1800 Candazo St, Marikina, 1800 Metro Manila",
        ContactNumber:"09182328723",
      },
      {
        Name:"Tapsi atbp",
        Type:"Restaurant",
        Location:"Bayan-Bayanan Avenue Cor. E Santos, Candazo St, Marikina, 1800 Metro Manila",
        ContactNumber:"(02) 8888 6236",
      },
      {
        Name:"Marikina Maternity Clinic and Lying-in",
        Type:"Health Facility",
        Location:"Bayan-Bayanan Ave, Marikina, 1800 Metro Manila",
        ContactNumber:"(02) 8948 0314",
      },
      {
        Name:"Little Angels Lying-in and Medical Clinic",
        Type:"Health Facility",
        Location:"Bayan-Bayanan Ave, Marikina, 1807 Metro Manila",
        ContactNumber:"09175683180",
      },
      {
        Name:"Mission Drug Store",
        Type:"Health Facility",
        Location:"15 Bayan-Bayanan Ave, Marikina, 1807 Metro Manila",
        ContactNumber:"09",
      },
      {
        Name:"Mercury Drug General Molina Branch",
        Type:"Health Facility",
        Location:"J. P. Rizal St, Marikina, 1800 Metro Manila",
        ContactNumber:"09175683180",
      },
      {
        Name:"Children's Clinic Dr. Alvin G. Santo",
        Type:"Health Facility",
        Location:"A. de Guzman St, Marikina, 1800 Metro Manila",
        ContactNumber:"(02) 8941 5302",
      },
      {
        Name:"St. Francis Generic Drug",
        Type:"Health Facility",
        Location:"A. de Guzman St, Marikina, 1800 Metro Manila",
        ContactNumber:"(02) 8941 53020",
      },
    ],
  },
  {
    name:"Marikina Heights",
    description:'During World War II, Barangay Marikina Heights was a vital military defense location...',
    image:"images/4.jpg",
    establisments:[
      {
        Name:"The Clay Oven Multicuisine Restaurant",
        Type:"Restaurant",
        Location:"Bayan-Bayanan Ave, Marikina, 1800 Metro Manila",
        ContactNumber:"09082593805",
      },
      {
        Name:"Angel’s Pizza - West Drive Marikina",
        Type:"Restaurant",
        Location:"Champagnat St, Marikina, 1800 Metro Manila",
        ContactNumber:"09",
      },
      {
        Name:"Pepetons Grill(Marikina)",
        Type:"Restaurant",
        Location:"1 SW Dao, corner Bayan-Bayanan Ave, Marikina, 1810 Metro Manila",
        ContactNumber:"(02) 7900 2004",
      },
      {
        Name:"Sweet Madies",
        Type:"Restaurant",
        Location:"42 Gen. Ordoñez St, Marikina, 1810 Metro Manila",
        ContactNumber:"(02) 7261 9869",
      },
      {
        Name:"Daddy’s Food and Resto",
        Type:"Restaurant",
        Location:"58 old 80 new SW Dao, Marikina, 1810 Metro Manila",
        ContactNumber:"09167044097",
      },
      {
        Name:"Garcia General Hospital",
        Type:"Health Facility",
        Location:"49 Bayan-Bayanan Ave, Marikina, 1800 Metro Manila",
        ContactNumber:"(02) 8941 5511",
      },
      {
        Name:"Tan-Villasanta Optical & Dental Clinic",
        Type:"Health Facility",
        Location:"53b Bayan-Bayanan Ave, Marikina, 1810 Metro Manila",
        ContactNumber:"09175683180",
      },
      {
        Name:"The Generics Pharmacy - Paraclete Building",
        Type:"Health Facility",
        Location:"M426+CJ Marikina, Metro Manila",
        ContactNumber:"(02) 8735 1389",
      },
      {
        Name:"Mercury Ayala Mall Marikina",
        Type:"Restaurant",
        Location:"Health Facility",
        ContactNumber:"J4X7+CXF, Liwasang Kalayaan, Marikina, 1800 Metro Manila",
      },
      {
        Name:"Marikina - 영도 ( Yeongdo ) Friendship Park",
        Type:"Landmarks",
        Location:"M428+7H9, Marikina, 1810 Metro Manila",
        ContactNumber:"(02) 8941 5302",
      },
      {
        Name:"Liwasang Kalayaan Park",
        Type:"Landmarks",
        Location:"M428+7H9, Marikina, 1810 Metro Manila",
        ContactNumber:"(02) 8941 5302",
      },
      {
        Name:"Marikorea Monument (Historical Landmark)",
        Type:"Landmarks",
        Location:"M428+4Q2, Marikina, 1800 Metro Manila",
        ContactNumber:"09321487016",
      },
      {
        Name:"Grotto Park",
        Type:"Landmarks",
        Location:"M428+72M, Marikina, 1800 Metro Manila",
        ContactNumber:"",
      },
      {
        Name:"Book Museum cum Ethnology Center",
        Type:"Museum",
        Location:"127, 199 SE Dao, Marikina, 1810 Metro Manila",
        ContactNumber:"(02) 8570 4449",
      },
      {
        Name:"Marikina Heights Barangay Hall",
        Type:"Government",
        Location:"J4X8+VWP, Bayan-Bayanan Ave, Marikina, 1800 Metro Manila",
        ContactNumber:"(02) 8942 0572",
      },
      {
        Name:"Marikina Police Station 9",
        Type:"Government",
        Location:"J4X8+WW6, East Dr, Marikina, 1800 Metro Manila",
        ContactNumber:"0289420572",
      }
    ]
  },
  {
    name:"Conception Dos",
    description:'Concepcion Dos also known to many as SSS Village is located near the Antipolo boundary. It is a place with many food hubs.',
    image:"images/5.jpg",
    establisments:[
      {
        Name:"Crazy Katsu",
        Type:"Restaurant",
        Location:"22 J. Molina, Corner L. De Guzman St, Marikina, 1800 Metro Manila",
        ContactNumber:"None",
      },
      {
        Name:"Snow the Cat cafe",
        Type:"Restaurant",
        Location:"1B, 95 Rainbow St, Marikina, 1811 Metro Manila",
        ContactNumber:"09687318893",
      },
      {
        Name:"Chipori Marikina (Main Branch)",
        Type:"Restaurant",
        Location:"60, 1811 Lilac St, Marikina, 1800 Metro Manila",
        ContactNumber:"09777058837",
      },
      {
        Name:"Chicken Studio",
        Type:"Restaurant",
        Location:"D Lilac St, Marikina, 1811 Metro Manila",
        ContactNumber:"09983046803",
      },
      {
        Name:"Forget Me Not Cafe",
        Type:"Restaurant",
        Location:"Hacienda Heights, 24 Lilac St, Marikina, 1811 Metro Manila",
        ContactNumber:"09178699104",
      },
      {
        Name:"Marikina House of Holiday Decorations",
        Type:"Museum",
        Location:"7 Sinai St, Marikina, 1800 Metro Manila",
        ContactNumber:"(02) 8948 0314",
      },
      {
        Name:"Eugene Torre Chess Museum",
        Type:"Museum",
        Location:"General Ordoñez, corner Maroon St, Marikina, 1811 Metro Manila",
        ContactNumber:"09175683180",
      },
      {
        Name:"Concepcion Dos Barangay Hall",
        Type:"Government",
        Location:"5 Pio del Pilar St, Marikina, 1800 Metro Manila",
        ContactNumber:"(02) 8942 0559",
      },
      {
        Name:"Concepcion Dos Health Center",
        Type:"Health Facility",
        Location:"Pio del Pilar St, Marikina, 1800 Metro Manila",
        ContactNumber:"None",
      },
      {
        Name:"Marikina City Police Station Pcp - 7",
        Type:"Government",
        Location:"66 Lilac St, Marikina, 1811 Metro Manila",
        ContactNumber:"(02) 8942 6101",
      },
      {
        Name:"Mercury Drug Concepcion Dos Lilac Branch",
        Type:"Health Facility",
        Location:"Lilac St, Marikina, 1811 Rizal",
        ContactNumber:"(02) 85341933",
      },
      {
        Name:"SDS Medical Center Inc.o",
        Type:"Health Facility",
        Location:"61 Katipunan St, Marikina, 1800 Metro Manila",
        ContactNumber:"79331405",
      },
      {
        Name:"Med Save (Pharmacy)",
        Type:"Health Facility",
        Location:"Panorama St, Marikina, 1800 Metro Manila",
        ContactNumber:"None",
      },
      {
        Name:"TGP The Generics Pharmacy",
        Type:"Health Facility",
        Location:"UNIT NO, 51-C Lilac St, Marikina, 1811 Metro Manila",
        ContactNumber:"None",
      },
    ],
  },
  {
    name:"Tumana",
    description:'Tumana is probably the most populated barangay in Marikina City; a former sitio of Concepcion Uno.',
    image:"images/6.jpg",
    establisments:[
      {
        Name:"Czyrah’s Pizza",
        Type:"Restaurant",
        Location:"19 Bagong Farmers Ave 1, Marikina, 1800 Metro Manila",
        ContactNumber:"None",
      },
      {
        Name:"Five Star Chicken Tumana",
        Type:"Restaurant",
        Location:"B-1 Farmers, Marikina, 1807 Metro Manila",
        ContactNumber:"(02) 8551 5828",
      },
      {
        Name:"PARJUAN’S III Pancit Malabon House(Tumana Branch)",
        Type:"Restaurant",
        Location:"Bagong Farmers Ave 1, Marikina, 1806 Metro Manila",
        ContactNumber:"09604711928",
      },
      {
        Name:"Kutiara - Tapsilog Pancit Atbp",
        Type:"Restaurant",
        Location:"Bagong Farmers Ave 1, Marikina, 1800 Metro Manila",
        ContactNumber:"09178326580",
      },
      {
        Name:"Infinitea Tumana Marikina (Cafe)	",
        Type:"Restaurant",
        Location:"Blk 1 Lot, 15 Bagong Farmers Ave 1, Marikina, 1800 Metro Manila",
        ContactNumber:"09162124970",
      },
      {
        Name:"Barangay Public Safety Office (Tumana)",
        Type:"Government",
        Location:"Blk 43 Farmers 1 Avenue, Marikina, 1805 Metro Manila",
        ContactNumber:"(02) 8477 3819",
      },
      {
        Name:"Marikina City Police Station PCP - 16	",
        Type:"Government",
        Location:"Farmers 1 Ave, Singkamas Street, Marikina, 1805 Metro Manila",
        ContactNumber:"(02) 3496 2637",
      },
      {
        Name:"Barangay Tumana Hall",
        Type:"Government",
        Location:"Marikina, 1800 Metro Manila",
        ContactNumber:"None",
      },
      {
        Name:"MMDA Tumana Impounding Area",
        Type:"Government",
        Location:"Marikina, 1800 Metro Manila",
        ContactNumber:"None",
      },
      {
        Name:"Tumana Health Center and Lying-In Clinic",
        Type:"Health Facility",
        Location:"105 Bagong Farmers Ave 1, Marikina, 1807 Bagong Farmers Ave 1, Marikina, 1807 Metro Manila",
        ContactNumber:"(02) 8941 5302",
      },
      {
        Name:"Generika Drugstore",
        Type:"Health Facility",
        Location:"679 Bagong Farmers 1 Ave, Marikina, 1805 Metro Manila",
        ContactNumber:"(02) 7625 5669",
      },
      {
        Name:"Verushka Pharmacy",
        Type:"Health Facility",
        Location:"Bagong Farmers Ave 1, Marikina, 1800 Metro Manila",
        ContactNumber:"09321487016",
      },
      {
        Name:"TGP - The Generics Pharmacy",
        Type:"Health Facility",
        Location:"Bagong Farmers Ave 1, Marikina, 1800 Metro Manila",
        ContactNumber:"09321487016",
      },
      {
        Name:"Adcare Pharmacy",
        Type:"Health Facility",
        Location:"Marikina, 1800 Metro Manila",
        ContactNumber:"None",
      },
      {
        Name:"Tumana Linear Park",
        Type:"Landmark",
        Location:"Marikina, 1800 Metro Manila",
        ContactNumber:"None",
      },
    ],
  }
]
